from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


__all__ = ["ChildAIAssessment"]


class ChildAIAssessment(models.Model):
    """Weekly-generated AI assessment for a child profile.

    One row per (child, week_start). Generated by the cron command
    `generate_parent_assessments` (Sunday noon) or admin "Regenerate" action.
    """

    child = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name="ai_assessments",
        verbose_name=_("child"),
    )
    generated_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name=_("generated at"),
    )
    week_start = models.DateField(
        db_index=True,
        verbose_name=_("week start (Monday)"),
        help_text=_("Monday of the ISO week this assessment covers."),
    )
    markdown = models.TextField(
        verbose_name=_("AI markdown report"),
    )
    suggested_problem_codes = models.JSONField(
        default=list,
        blank=True,
        verbose_name=_("suggested problem codes"),
        help_text=_("Problem codes referenced in the report; rendered as cards."),
    )
    model_used = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_("OpenAI model used"),
    )
    prompt_tokens = models.IntegerField(default=0, verbose_name=_("prompt tokens"))
    completion_tokens = models.IntegerField(default=0, verbose_name=_("completion tokens"))

    class Meta:
        unique_together = ("child", "week_start")
        ordering = ("-week_start",)
        verbose_name = _("Child AI assessment")
        verbose_name_plural = _("Child AI assessments")

    def __str__(self):
        return f"{self.child.username} – week of {self.week_start}"
