from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


__all__ = ["ChildAIAssessment", "ClassSchedule"]


DAY_OF_WEEK_CHOICES = (
    (0, _("Thứ Hai")),
    (1, _("Thứ Ba")),
    (2, _("Thứ Tư")),
    (3, _("Thứ Năm")),
    (4, _("Thứ Sáu")),
    (5, _("Thứ Bảy")),
    (6, _("Chủ Nhật")),
)


class ChildAIAssessment(models.Model):
    """Weekly-generated AI assessment for a child profile.

    One row per (child, week_start). Generated by the cron command
    `generate_parent_assessments` (Sunday noon) or admin "Regenerate" action.
    """

    child = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name="ai_assessments",
        verbose_name=_("child"),
    )
    generated_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name=_("generated at"),
    )
    week_start = models.DateField(
        db_index=True,
        verbose_name=_("week start (Monday)"),
        help_text=_("Monday of the ISO week this assessment covers."),
    )
    markdown = models.TextField(
        verbose_name=_("AI markdown report"),
    )
    suggested_problem_codes = models.JSONField(
        default=list,
        blank=True,
        verbose_name=_("suggested problem codes"),
        help_text=_("Problem codes referenced in the report; rendered as cards."),
    )
    model_used = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_("OpenAI model used"),
    )
    prompt_tokens = models.IntegerField(default=0, verbose_name=_("prompt tokens"))
    completion_tokens = models.IntegerField(default=0, verbose_name=_("completion tokens"))

    class Meta:
        unique_together = ("child", "week_start")
        ordering = ("-week_start",)
        verbose_name = _("Child AI assessment")
        verbose_name_plural = _("Child AI assessments")

    def __str__(self):
        return f"{self.child.username} – week of {self.week_start}"


class ClassSchedule(models.Model):
    """Lịch học hàng tuần của một TeacherClass.

    Mỗi học sinh thuộc một (hoặc nhiều) TeacherClass sẽ kế thừa lịch học
    của lớp đó. Lịch lặp lại hàng tuần — mỗi entry mô tả 1 buổi học cố định
    (vd: "Thứ Hai 19:00-21:00 - Cấu trúc dữ liệu - thầy Hùng - phòng A101").
    """

    teacher_class = models.ForeignKey(
        "judge.TeacherClass",
        on_delete=models.CASCADE,
        related_name="class_schedules",
        verbose_name=_("Lớp"),
    )
    day_of_week = models.IntegerField(
        choices=DAY_OF_WEEK_CHOICES,
        verbose_name=_("Thứ"),
    )
    start_time = models.TimeField(verbose_name=_("Giờ bắt đầu"))
    end_time = models.TimeField(verbose_name=_("Giờ kết thúc"))
    subject = models.CharField(
        max_length=200,
        verbose_name=_("Môn / Buổi học"),
        help_text=_("VD: Tin học - Cấu trúc dữ liệu"),
    )
    teacher = models.CharField(
        max_length=200, blank=True, verbose_name=_("Giáo viên")
    )
    location = models.CharField(
        max_length=200, blank=True, verbose_name=_("Phòng / Địa điểm")
    )
    notes = models.TextField(blank=True, verbose_name=_("Ghi chú"))
    is_active = models.BooleanField(default=True, verbose_name=_("Đang áp dụng"))
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("day_of_week", "start_time")
        verbose_name = _("Lịch học")
        verbose_name_plural = _("Lịch học")

    def __str__(self):
        return (
            f"{self.teacher_class.name}: "
            f"{self.get_day_of_week_display()} "
            f"{self.start_time.strftime('%H:%M')}–"
            f"{self.end_time.strftime('%H:%M')} {self.subject}"
        )
