# Generated by Django 5.2.14 on 2026-05-08 13:19

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0241_widen_contest_problem_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='Students this profile (a parent) is allowed to monitor.', related_name='parents', to='judge.profile', verbose_name='children'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[('user', 'Normal User'), ('setter', 'Problem Setter'), ('admin', 'Admin'), ('parent', 'Parent')], db_index=True, default='user', max_length=10, verbose_name='display rank'),
        ),
        migrations.CreateModel(
            name='ChildAIAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='generated at')),
                ('week_start', models.DateField(db_index=True, help_text='Monday of the ISO week this assessment covers.', verbose_name='week start (Monday)')),
                ('markdown', models.TextField(verbose_name='AI markdown report')),
                ('suggested_problem_codes', models.JSONField(blank=True, default=list, help_text='Problem codes referenced in the report; rendered as cards.', verbose_name='suggested problem codes')),
                ('model_used', models.CharField(blank=True, max_length=64, verbose_name='OpenAI model used')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='prompt tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='completion tokens')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to='judge.profile', verbose_name='child')),
            ],
            options={
                'verbose_name': 'Child AI assessment',
                'verbose_name_plural': 'Child AI assessments',
                'ordering': ('-week_start',),
                'unique_together': {('child', 'week_start')},
            },
        ),
    ]
