# Generated by Django 5.2.14 on 2026-05-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0242_profile_children_alter_profile_display_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Thứ')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('subject', models.CharField(help_text='VD: Tin học - Cấu trúc dữ liệu', max_length=200, verbose_name='Môn / Buổi học')),
                ('teacher', models.CharField(blank=True, max_length=200, verbose_name='Giáo viên')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Phòng / Địa điểm')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='judge.organization', verbose_name='Lớp / Tổ chức')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
                'ordering': ('day_of_week', 'start_time'),
            },
        ),
    ]
