# Generated by Django 5.2.14 on 2026-05-15 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0243_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAIScore',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_score', serialize=False, to='judge.submission')),
                ('score', models.FloatField(db_index=True, default=0.0, help_text='Combined 0-100, higher = more suspicious')),
                ('stylometry_score', models.FloatField(blank=True, help_text='0-100; null if no baseline yet', null=True)),
                ('markers_score', models.FloatField(default=0.0)),
                ('markers_found', models.JSONField(default=list)),
                ('baseline_size', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI suspicion score',
                'verbose_name_plural': 'AI suspicion scores',
                'ordering': ('-score',),
            },
        ),
    ]
