# Generated by Django 5.2.14 on 2026-05-19 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0244_submissionaiscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Trường'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zalo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Zalo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[('user', 'Normal User'), ('setter', 'Problem Setter'), ('admin', 'Admin'), ('parent', 'Parent'), ('teacher', 'Teacher')], db_index=True, default='user', max_length=10, verbose_name='display rank'),
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('yeu', 'Yếu'), ('tb', 'Trung bình'), ('kha', 'Khá'), ('tot', 'Tốt'), ('xuat_sac', 'Xuất sắc')], max_length=10, verbose_name='Học lực')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm đánh giá')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='judge.organization', verbose_name='Lớp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='judge.profile', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Học lực',
                'verbose_name_plural': 'Học lực',
                'ordering': ('-evaluated_at',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Ngày học')),
                ('present', models.BooleanField(default=False, verbose_name='Có mặt')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='judge.organization', verbose_name='Lớp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='judge.profile', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'ordering': ('-date', 'student_id'),
                'unique_together': {('student', 'organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TuitionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, help_text='Ngày đầu tiên của tháng được tính học phí (vd 2026-05-01).', verbose_name='Kỳ học phí')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Học phí (VNĐ)')),
                ('paid', models.BooleanField(db_index=True, default=False, verbose_name='Đã đóng')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đóng')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_records', to='judge.organization', verbose_name='Lớp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_records', to='judge.profile', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Học phí',
                'verbose_name_plural': 'Học phí',
                'ordering': ('-period', 'student_id'),
                'unique_together': {('student', 'organization', 'period')},
            },
        ),
    ]
