# Generated by Django 5.2.14 on 2026-05-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0250_sessionnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionrecord',
            name='period',
            field=models.DateField(db_index=True, help_text='Ngày đầu tháng (vd 2026-05-01).', verbose_name='Kỳ học phí'),
        ),
        migrations.CreateModel(
            name='ClassAISummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='Tuần (thứ Hai)')),
                ('generated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Sinh lúc')),
                ('markdown', models.TextField(verbose_name='Nội dung (Markdown)')),
                ('model_used', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='judge.teacherclass', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Tổng kết AI của lớp',
                'verbose_name_plural': 'Tổng kết AI của lớp',
                'ordering': ('-week_start',),
                'unique_together': {('teacher_class', 'week_start')},
            },
        ),
    ]
