# Generated by Django 5.2.14 on 2026-06-03 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0257_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='key',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Contest id must be ^[a-z0-9_]+$')], verbose_name='contest id'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(help_text='A short, unique code for the problem, used in the url after /problem/', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Problem code must be ^[a-z0-9_]+$')], verbose_name='problem code'),
        ),
    ]
